### ISSUE TITLE
Fails to start with fresh clone and npm run start

### ISSUE THREAD

**Issue by solsson** [substance/texture#195]
I've tried both with Node 8 / NPM 5, and with `docker run -ti --entrypoint /bin/bash -p 5555:5555 -v $(pwd):/usr/src/app node:6.10`.

```bash
root@eeb1352715b9:/usr/src/app# npm install
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.10.2
npm info attempt registry request try #1 at 11:53:19 AM
npm http request GET https://registry.npmjs.org/lodash
npm info git [ 'clone',
npm info git   '--template=/root/.npm/_git-remotes/_templates',
npm info git   '--mirror',
npm info git   'git://github.com/substance/substance.git',
npm info git   '/root/.npm/_git-remotes/git-github-com-substance-substance-git-develop-40c2231b' ]
npm http 200 https://registry.npmjs.org/lodash
npm info retry fetch attempt 1 at 11:53:20 AM
npm info attempt registry request try #1 at 11:53:20 AM
npm http fetch GET https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz
npm http fetch 200 https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz
npm info git [ 'rev-list', '-n1', 'develop' ]
npm info git [ 'clone',
npm info git   '/root/.npm/_git-remotes/git-github-com-substance-substance-git-develop-40c2231b',
npm info git   '/tmp/npm-18-6a364c34/git-cache-8c0d5256/5bded1591d65003de8c379fbe42962d8e1b8b241' ]
npm info git [ 'checkout', '5bded1591d65003de8c379fbe42962d8e1b8b241' ]
npm info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/lodash-es
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/boolbase
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/css-what
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/domelementtype
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/entities
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/nth-check
npm http 200 https://registry.npmjs.org/lodash-es
npm http 200 https://registry.npmjs.org/boolbase
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/lodash-es/-/lodash-es-4.13.1.tgz
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz
npm http fetch 200 https://registry.npmjs.org/lodash-es/-/lodash-es-4.13.1.tgz
npm http fetch 200 https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz
npm http 200 https://registry.npmjs.org/domelementtype
npm http 200 https://registry.npmjs.org/nth-check
npm http 200 https://registry.npmjs.org/entities
npm http 200 https://registry.npmjs.org/css-what
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/nth-check/-/nth-check-1.0.1.tgz
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/entities/-/entities-1.1.1.tgz
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/css-what/-/css-what-2.1.0.tgz
npm http fetch 200 https://registry.npmjs.org/nth-check/-/nth-check-1.0.1.tgz
npm http fetch 200 https://registry.npmjs.org/entities/-/entities-1.1.1.tgz
npm http fetch 200 https://registry.npmjs.org/css-what/-/css-what-2.1.0.tgz
npm http fetch 200 https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/font-awesome
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/substance-bundler
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/substance-test
npm http 200 https://registry.npmjs.org/font-awesome
npm http 200 https://registry.npmjs.org/substance-test
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/font-awesome/-/font-awesome-4.5.0.tgz
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/substance-test/-/substance-test-0.5.1.tgz
npm http 200 https://registry.npmjs.org/substance-bundler
npm info retry fetch attempt 1 at 11:53:30 AM
npm info attempt registry request try #1 at 11:53:30 AM
npm http fetch GET https://registry.npmjs.org/substance-bundler/-/substance-bundler-0.18.4.tgz
npm http fetch 200 https://registry.npmjs.org/substance-test/-/substance-test-0.5.1.tgz
npm http fetch 200 https://registry.npmjs.org/font-awesome/-/font-awesome-4.5.0.tgz
npm http fetch 200 https://registry.npmjs.org/substance-bundler/-/substance-bundler-0.18.4.tgz
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/source-map-support
npm info attempt registry request try #1 at 11:53:30 AM
npm http request GET https://registry.npmjs.org/fsevents
npm http 200 https://registry.npmjs.org/source-map-support
npm http 304 https://registry.npmjs.org/fsevents
npm info retry fetch attempt 1 at 11:53:31 AM
npm info attempt registry request try #1 at 11:53:31 AM
npm http fetch GET https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.15.tgz
npm http fetch 200 https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.15.tgz
npm info attempt registry request try #1 at 11:53:31 AM
npm http request GET https://registry.npmjs.org/source-map
npm http 200 https://registry.npmjs.org/source-map
npm info retry fetch attempt 1 at 11:53:31 AM
npm info attempt registry request try #1 at 11:53:31 AM
npm http fetch GET https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz
npm http fetch 200 https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz
npm info retry fetch attempt 1 at 11:53:31 AM
npm info attempt registry request try #1 at 11:53:31 AM
npm http fetch GET https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.3.tgz
npm http fetch 200 https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.3.tgz
npm info lifecycle substance-texture@1.0.0-alpha.2~preinstall: substance-texture@1.0.0-alpha.2
npm info lifecycle boolbase@1.0.0~preinstall: boolbase@1.0.0
npm info lifecycle css-what@2.1.0~preinstall: css-what@2.1.0
npm info lifecycle domelementtype@1.3.0~preinstall: domelementtype@1.3.0
npm info lifecycle entities@1.1.1~preinstall: entities@1.1.1
npm info lifecycle lodash-es@4.13.1~preinstall: lodash-es@4.13.1
npm info lifecycle nth-check@1.0.1~preinstall: nth-check@1.0.1
npm info lifecycle source-map@0.5.6~preinstall: source-map@0.5.6
npm info lifecycle source-map-support@0.4.15~preinstall: source-map-support@0.4.15
npm info lifecycle source-map-support@0.4.3~preinstall: source-map-support@0.4.3
npm info lifecycle font-awesome@4.5.0~preinstall: font-awesome@4.5.0
npm info lifecycle lodash@4.17.4~preinstall: lodash@4.17.4
npm info lifecycle substance@1.0.0-beta.7-preview.10~preinstall: substance@1.0.0-beta.7-preview.10
npm info lifecycle substance-bundler@0.18.4~preinstall: substance-bundler@0.18.4
npm info lifecycle substance-test@0.5.1~preinstall: substance-test@0.5.1
npm info linkStuff boolbase@1.0.0
npm info linkStuff css-what@2.1.0
npm info linkStuff domelementtype@1.3.0
npm info linkStuff entities@1.1.1
npm info linkStuff lodash-es@4.13.1
npm info linkStuff nth-check@1.0.1
npm info linkStuff source-map@0.5.6
npm info linkStuff source-map-support@0.4.15
npm info linkStuff source-map-support@0.4.3
npm info linkStuff font-awesome@4.5.0
npm info linkStuff lodash@4.17.4
npm info linkStuff substance@1.0.0-beta.7-preview.10
npm info linkStuff substance-bundler@0.18.4
npm info linkStuff substance-test@0.5.1
npm info lifecycle boolbase@1.0.0~install: boolbase@1.0.0
npm info lifecycle css-what@2.1.0~install: css-what@2.1.0
npm info lifecycle domelementtype@1.3.0~install: domelementtype@1.3.0
npm info lifecycle entities@1.1.1~install: entities@1.1.1
npm info lifecycle lodash-es@4.13.1~install: lodash-es@4.13.1
npm info lifecycle nth-check@1.0.1~install: nth-check@1.0.1
npm info lifecycle source-map@0.5.6~install: source-map@0.5.6
npm info lifecycle source-map-support@0.4.15~install: source-map-support@0.4.15
npm info lifecycle source-map-support@0.4.3~install: source-map-support@0.4.3
npm info lifecycle font-awesome@4.5.0~install: font-awesome@4.5.0
npm info lifecycle lodash@4.17.4~install: lodash@4.17.4
npm info lifecycle substance@1.0.0-beta.7-preview.10~install: substance@1.0.0-beta.7-preview.10
npm info lifecycle substance-bundler@0.18.4~install: substance-bundler@0.18.4
npm info lifecycle substance-test@0.5.1~install: substance-test@0.5.1
npm info lifecycle boolbase@1.0.0~postinstall: boolbase@1.0.0
npm info lifecycle css-what@2.1.0~postinstall: css-what@2.1.0
npm info lifecycle domelementtype@1.3.0~postinstall: domelementtype@1.3.0
npm info lifecycle entities@1.1.1~postinstall: entities@1.1.1
npm info lifecycle lodash-es@4.13.1~postinstall: lodash-es@4.13.1
npm info lifecycle nth-check@1.0.1~postinstall: nth-check@1.0.1
npm info lifecycle source-map@0.5.6~postinstall: source-map@0.5.6
npm info lifecycle source-map-support@0.4.15~postinstall: source-map-support@0.4.15
npm info lifecycle source-map-support@0.4.3~postinstall: source-map-support@0.4.3
npm info lifecycle font-awesome@4.5.0~postinstall: font-awesome@4.5.0
npm info lifecycle lodash@4.17.4~postinstall: lodash@4.17.4
npm info lifecycle substance@1.0.0-beta.7-preview.10~postinstall: substance@1.0.0-beta.7-preview.10
npm info lifecycle substance-bundler@0.18.4~postinstall: substance-bundler@0.18.4
npm info lifecycle substance-test@0.5.1~postinstall: substance-test@0.5.1
npm info linkStuff substance-texture@1.0.0-alpha.2
npm info lifecycle substance-texture@1.0.0-alpha.2~install: substance-texture@1.0.0-alpha.2
npm info lifecycle substance-texture@1.0.0-alpha.2~postinstall: substance-texture@1.0.0-alpha.2
npm info lifecycle substance-texture@1.0.0-alpha.2~prepublish: substance-texture@1.0.0-alpha.2
substance-texture@1.0.0-alpha.2 /usr/src/app
+-- font-awesome@4.5.0 
+-- lodash@4.17.4 
+-- substance@1.0.0-beta.7-preview.10  (git://github.com/substance/substance.git#5bded1591d65003de8c379fbe42962d8e1b8b241)
| +-- boolbase@1.0.0 
| +-- css-what@2.1.0 
| +-- domelementtype@1.3.0 
| +-- entities@1.1.1 
| +-- lodash-es@4.13.1 
| `-- nth-check@1.0.1 
+-- substance-bundler@0.18.4 
| `-- source-map-support@0.4.15 
|   `-- source-map@0.5.6 
`-- substance-test@0.5.1 
  `-- source-map-support@0.4.3 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/substance-bundler/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm info ok 
root@eeb1352715b9:/usr/src/app# npm run start
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.10.2
npm info lifecycle substance-texture@1.0.0-alpha.2~prestart: substance-texture@1.0.0-alpha.2
npm info lifecycle substance-texture@1.0.0-alpha.2~start: substance-texture@1.0.0-alpha.2

> substance-texture@1.0.0-alpha.2 start /usr/src/app
> node make dev -s -w

Remove: tmp/
Creating virtual file system: tmp/vfs.js
..finished in 94 ms.
Compiling schema 'JATS-publishing'...

Error during execution of Command  custom
Error: Cannot find module 'substance'
Stacktrace:
Error: Cannot find module 'substance'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at CustomAction.execute [as _execute] (/usr/src/app/make.js:111:63)
    at CustomAction.execute (/usr/src/app/node_modules/substance-bundler/src/commands/CustomCommand.js:152:33)
    at CustomCommand._executeWithCollection (/usr/src/app/node_modules/substance-bundler/src/commands/CustomCommand.js:105:27)
    at CustomCommand.execute (/usr/src/app/node_modules/substance-bundler/src/commands/CustomCommand.js:36:19)
    at Bundler._next (/usr/src/app/node_modules/substance-bundler/src/Bundler.js:289:30)
    at Bundler._step (/usr/src/app/node_modules/substance-bundler/src/Bundler.js:330:12)

npm info lifecycle substance-texture@1.0.0-alpha.2~start: Failed to exec start script
npm ERR! Linux 4.9.31-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! substance-texture@1.0.0-alpha.2 start: `node make dev -s -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the substance-texture@1.0.0-alpha.2 start script 'node make dev -s -w'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the substance-texture package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node make dev -s -w
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs substance-texture
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls substance-texture
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by michael** [comment]
Please use the old version from the master branch for now, the reason for this error is that we haven't pinned down the dependency of substance to a version yet. A release will follow in a few days including a substance npm release.

**Comment by solsson** [comment]
I'll just wait a couple of days then :) With master I get a different error
```Error during execution of Command  make
Error: Cannot find module 'substance/make.js'
Stacktrace:
Error: Cannot find module 'substance/make.js'
```

**Comment by michael** [comment]
Oh sorry for that, but let's look forward! :)
