### ISSUE TITLE
Error: Cannot find module 'substance'

### ISSUE THREAD

**Issue by samboustani** [substance/texture#525]
npm install

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-ltDNYQ69WNS03pzAxoKM2pnHVI8= integrity checksum failed when using sha1: wanted sha1-ltDNYQ69WNS03pzAxoKM2pnHVI8= but got sha512-bAdJv7fBLhWC+/Bls0Oza+mvTaNQtP+1RyhhhvD95pgUJz6XM5IzgmxOkItJ9tkoCiplvAnXI1tNmmUD/eScyA==. (73721 bytes)

npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> substance-texture@1.0.0-preview.1.13 start C:\Users\sam.boustani\source\repos\texture
> node make web -s -w -d data

Compiling schema 'JATS-publishing'...

**Error during execution of Command  custom
Error: Cannot find module 'substance'**
Stacktrace:
Error: Cannot find module 'substance'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

> substance-texture@1.0.0-preview.1.13 prepare C:\Users\sam\source\repos\texture
> node make publish

Remove: tmp/
Compiling schema 'JATS-publishing'...

Error during execution of Command  custom
TypeError: compileRNG is not a function
Stacktrace:
TypeError: compileRNG is not a function
    at CustomAction.execute [as _execute] (C:\Users\sam\source\repos\texture\make.js:357:25)
    at CustomAction.execute (C:\Users\sam\source\repos\texture\node_modules\substance-bundler\src\commands\CustomCommand.js:152:33)
    at CustomCommand._executeWithCollection (C:\Users\sam\source\repos\texture\node_modules\substance-bundler\src\commands\CustomCommand.js:105:27)
    at CustomCommand.execute (C:\Users\sam\source\repos\texture\node_modules\substance-bundler\src\commands\CustomCommand.js:36:19)
    at Bundler._next (C:\Users\sam\source\repos\texture\node_modules\substance-bundler\src\Bundler.js:305:30)
    at Bundler._step (C:\Users\sam\source\repos\texture\node_modules\substance-bundler\src\Bundler.js:346:12)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! substance-texture@1.0.0-preview.1.13 prepare: `node make publish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the substance-texture@1.0.0-preview.1.13 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

from log...

716 silly lifecycle substance-texture@1.0.0-preview.1.13~prepare: Args: [ '/d /s /c', 'node make publish' ]
717 silly lifecycle substance-texture@1.0.0-preview.1.13~prepare: Returned: code: 1  signal: null
718 info lifecycle substance-texture@1.0.0-preview.1.13~prepare: Failed to exec prepare script
719 verbose stack Error: substance-texture@1.0.0-preview.1.13 prepare: `node make publish`
719 verbose stack Exit status 1

723 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
724 verbose node v8.11.1
725 verbose npm  v5.6.0
726 error code ELIFECYCLE
727 error errno 1
728 error substance-texture@1.0.0-preview.1.13 prepare: `node make publish`
728 error Exit status 1
729 error Failed at the substance-texture@1.0.0-preview.1.13 prepare script.

**Comment by oliver----** [comment]
This must be something with your setup. Maybe you have `npm linked` substance. Maybe wiping `node_modules` and `npm install` helps.
